// <auto-generated />
using System;
using Lab_4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab_4.Migrations
{
    [DbContext(typeof(HireContext))]
    partial class HireContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab_4.Models.Hire", b =>
                {
                    b.Property<int>("HireId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ClientCode")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DateIssue")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateReturn")
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionGoods")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullNameClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NameGoods")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PriceGoods")
                        .HasColumnType("int");

                    b.Property<int>("PriceHireOnDay")
                        .HasColumnType("int");

                    b.HasKey("HireId");

                    b.ToTable("Hire");
                });
#pragma warning restore 612, 618
        }
    }
}
